version: "3.8"

services:

  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp-network

  odoo:
    image: odoo:16
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      ADMIN_PASSWD: ${ODOO_ADMIN_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
    networks:
      - erp-network

  fastapi:
    build:
      context: .
      dockerfile: fastapi_service/dockerfile
    container_name: fastapi-app
    env_file:
      - .env
    depends_on:
      - odoo
    ports:
      - "8000:8000"
    networks:
      - erp-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - erp-network

volumes:
  postgres_data:
  odoo-web-data:
  jenkins_home:
    external: true

networks:
  erp-network:
