FROM python:3.10

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy backend + frontend
COPY . /app

# Explicitly ensure templates and static are included
COPY ./templates /app/templates
COPY ./static /app/static

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
